// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"app/global"
	"app/internal/modules/user/controller"
	"app/internal/modules/user/repo"
	"app/internal/modules/user/service"
	"app/internal/third_party/redis"
	"gorm.io/gorm"
)

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	db := ProvideDB()
	iUserRepository := repo.NewUserRepository(db)
	redisProvider := redis.NewRedisProvider()
	iUserService := service.NewUserService(iUserRepository, redisProvider)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}

// user.wire.go:

func ProvideDB() *gorm.DB {
	return global.Postgres
}
